### ISSUE TITLE
Request for C# connector

### ISSUE THREAD

**Issue by asgaralim** [meteomatics/cpp-connector-api#1]
Hi All,

I want to get weather data for a region as a grid and /bin format. I would like to know file format of bin and how read/parse and save the file using .Net C# code. Could you please provide reference link where i can find the code snippet.
Thank you,

**Comment by meteomatics** [comment]
Hi asgaralim

I suppose we had a call recently and solved the issue there. In case I confused you with another customer, please contact us via our support email to open a new case.

Kind regards,
Christian
